#pragma once

#undef MACHINE_STYLE
#define MACHINE_STYLE POLARGRAPH

#undef MOTHERBOARD
#define MOTHERBOARD BOARD_SANGUINOLULU

#undef MACHINE_HARDWARE_VERSION
#define MACHINE_HARDWARE_VERSION MAKELANGELO_5
